### ISSUE TITLE
Directions method to return the `NSURLSessionDataTask`

### ISSUE THREAD

**Issue by markst** [marciniwanicki/OCGoogleDirectionsAPI#10]
We need to be able to cancel tasks, as we spin off multiple directions network requests.

**Comment by marciniwanicki** [comment]
Hi @markst,

Thank you for letting me know about this issue. 
I've checked your commit 480bb5e and it looks quite OK. Maybe instead of changing currently existing method header 
`- (void)directions:(OCDirectionsRequest *)request response:(OCDirectionsRequestCallback)callback;`
it would be good to add another one for those who need direct access to Task object i.e.
`- (NSURLSessionDataTask *)dataTaskWithRequest:(OCDirectionsRequest *)request response:(OCDirectionsRequestCallback)callback;`.

From my perspective `dataTaskWithRequest` method doesn't even need to call `[task resume]`. It might act as a factory for `NSURLSessionDataTask *` so then we will be able to refactor `- (void)directions:(OCDirectionsRequest *)request response:(OCDirectionsRequestCallback)callback;` so basically it might look like this: 
```objc
- (void)directions:(OCDirectionsRequest *)request response:(OCDirectionsRequestCallback)callback {
   NSURLSessionDataTask *task = [self dataTaskWithRequest:request response:response];
   [task resume];
}
```

I would love to see this in a pull request so fell free to make one if you have time.

Thanks again!

**Comment by markst** [comment]
Something like that @marciniwanicki ?

**Comment by marciniwanicki** [comment]
@markst yes, exactly like that! 👍 Thanks for the great contribution, I'll release new version in a minute.
