### ISSUE TITLE
Doesn't work with multiple waypoints

### ISSUE THREAD

**Issue by risp** [marciniwanicki/OCGoogleDirectionsAPI#9]
When using multiple waypoints the URL becomes something like this: `waypoints=52.221539,6.893662|50.948467,5.769674`

The problem is the `|` character, NSURL doesn't allow this character. To fix this simply escape the string. 
```
- (NSURL *)urlFromRequest:(OCDirectionsRequest *)request useHttps:(BOOL)useHttps andKey:(NSString *)key {
    OCAssertParameterNotNil(request, @"Request is nil.");
    OCAssertParameterNotNil(key, @"Key is nil.");

    NSString *requestString = [self stringFromRequest:request useHttps:useHttps andKey:key];
    NSURL *url = [[NSURL alloc] initWithString:requestString];
    return url;
}
```

becomes
```
- (NSURL *)urlFromRequest:(OCDirectionsRequest *)request useHttps:(BOOL)useHttps andKey:(NSString *)key {
    OCAssertParameterNotNil(request, @"Request is nil.");
    OCAssertParameterNotNil(key, @"Key is nil.");

    NSString *requestString = [self stringFromRequest:request useHttps:useHttps andKey:key];
    NSString *urlStr = [requestString stringByAddingPercentEscapesUsingEncoding:NSUTF8StringEncoding];
    NSURL *url = [[NSURL alloc] initWithString:urlStr];
    return url;
}
```

**Comment by marciniwanicki** [comment]
Thanks @risp for the catch. I introduced this issue in ver 0.1.5 as I'd tried to replace deprecated calls (including `stringByAddingPercentEscapesUsingEncoding:NSUTF8StringEncoding`). The current implementation is not perfect but at least should work for the waypoints parameter.
You can improve it if you have time (related files: `OCDirectionsRequestURLCreatorJSON.m`, `OCDirectionsRequestURLCreatorJSONTests.m`).

Podspec 0.1.6 with the fix is already pushed.
